# Generated by Django 5.2.4 on 2025-10-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_collections', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Brand/Collection this product belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_products', to='product_collections.productcollection'),
        ),
    ]
