# Generated by Django 5.0.1 on 2025-12-12 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('promotion', 'Promotion'), ('sale', 'Sale'), ('new_arrival', 'New Arrival'), ('info', 'Information'), ('warning', 'Warning')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_on_shop', models.BooleanField(default=True)),
                ('show_on_all_pages', models.BooleanField(default=False)),
                ('background_color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=7)),
                ('link_url', models.URLField(blank=True, help_text='Optional link for the announcement', null=True)),
                ('link_text', models.CharField(blank=True, help_text='Text for the link button', max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
