# Generated by Django 5.2.4 on 2025-10-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcollection',
            name='products',
        ),
    ]
